export const CREATE_KONDOS = "CREATE_KONDOS";
export const RETRIEVE_KONDOS = "RETRIEVE_KONDOS";
export const UPDATE_KONDOS = "UPDATE_KONDOS";
export const DELETE_KONDOS = "DELETE_KONDOS";
export const DELETE_ALL_KONDOS = "DELETE_ALL_KONDOS";
export const POPULATE_KONDOS = "POPULATE_KONDOS";